### Login Route
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "domotswiri@gmail.com",
  "password": "password123"
}

### Profile GET Route
GET http://localhost:4000/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjgwNzY1MzcsImV4cCI6MTYzMDY2ODUzNywiYXVkIjoiNjEwOTkwYmRhNjJkMGQxNTAwNzc3MGJkIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.51RpSAXw__AkEkJeVsm-ONyFWcBPlOcPDsl9mXXOTJE